plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-conjure-plugin:conjure-plugin:6.66.0
        checksums:
          darwin-amd64: 37c7493582a04a1a8962bf650dec20a53469ff9813d930320b03dfe1dbce6d60
          linux-amd64: adf56afe574db83990685d81d7e686a7b115cfde26b76a833ed4ec38116f8baa
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.42.0
        checksums:
          darwin-amd64: 67daeb93d6022bdfca282bd9e878a40a30992ae087e39fd8cf06c208ea8e9333
          linux-amd64: 716e2fd13e7104b67d55b9d63527a8900656082be0d1bbca848c3af83cc91e5d
    - locator:
        id: com.palantir.godel-refreshables-plugin:refreshables-plugin:0.224.0
        checksums:
          darwin-amd64: 5c35bce4537650c1caa7312a3c219bca71366cf9b1a827fb2c7f2968a2cc29ab
          linux-amd64: b12f7b6ffc250a3955640f769a292b985d44a76fff1c6ab77b8c012196007d14
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
  paths:
    - godel
    - conjure
