plugins:
  resolvers:
    - https://palantir.bintray.com/releases/{{GroupPath}}/{{Product}}/{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-conjure-plugin:conjure-plugin:4.0.0
        checksums:
          darwin-amd64: 90869bfd1e886c36fe9796e0964eb5e3adb39b3b5c68ea3a4f171b9423243200
          linux-amd64: b12b4a9659726db42d235a2267518c76e60c3e9496ba86a2ba97af5ebee69a7f
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.0.1
        checksums:
          darwin-amd64: df22922bacfe4e4e7c255607a0aace176205f04ae001f3746276fcfab1780e01
          linux-amd64: a2697b3d504bb37c2fd8831a66c7014927a6d94e4dfb9765b4764354370a1ab6
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
  - \..+
  - vendor
  paths:
  - godel
  - conjure
  - witchcraft/internal/negroni
