plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-conjure-plugin:conjure-plugin:6.50.0
        checksums:
          darwin-amd64: 564c43fdb2e6322de9c4ebef76ec09737e1228c3615d7ab8383a335485616958
          linux-amd64: a9fb520586859afd05160fdcefd4b6318d964484ea08a63d26dfe1961dea93b4
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.28.0
        checksums:
          darwin-amd64: 23b20091ec8f749853b218ece9761aef3f241e1d4a0552bd6b120038ce674f61
          linux-amd64: 7416ae82c7bb8ef82f0fcc3837b2a7cdc72d81fc8cf53cffd01c76d37d40b762
    - locator:
        id: com.palantir.godel-refreshables-plugin:refreshables-plugin:0.143.0
        checksums:
          darwin-amd64: b3fb3ac452c0be05929ccf4ab0999c651e63992aa6e186397b781b2ad203aa90
          linux-amd64: e83422491544bee2e83a960cd1ac71cb55c3954bb2a07e984fb9716ea35740b5
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
  paths:
    - godel
    - conjure
