plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-conjure-plugin:conjure-plugin:6.64.0
        checksums:
          darwin-amd64: e400a8ad1d278b4dceac76773ae2588619bedd5ae22d302892d4725459bb2fb6
          linux-amd64: 2e844b82c6cdb58eda2f88d2c5aa2a494aa6e929203479a9c18e22bbbd786558
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.40.0
        checksums:
          darwin-amd64: e29fef2cac0680597653deaa7e5ab904498497ad71fd53346a4ae19c37e929be
          linux-amd64: 6c028e3beac58ce9622f143ffb99cd014ce296e3367f4bfb10e12bccb50d444a
    - locator:
        id: com.palantir.godel-refreshables-plugin:refreshables-plugin:0.217.0
        checksums:
          darwin-amd64: fd23ab910615de2c860c084729fa3b460fa8670f46ff60bb7fab6d0b08dfb6d8
          linux-amd64: c4e9f2d822338a8bfd11c2addb5d1046ddaac89c465a17a678f7626fb716b8b7
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
  paths:
    - godel
    - conjure
