plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-conjure-plugin:conjure-plugin:6.37.0
        checksums:
          darwin-amd64: ee325bc460969234a9a2b5375ab3074946f55cb16626914a875570abca805e34
          linux-amd64: 04de909f96528fd945ba86ab74e43fb304d3de66e36b84eb548b1a03c13d8bae
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.22.0
        checksums:
          darwin-amd64: d7e234ced02bdf43f83d15416fc3f8d9c6fd1874ed7cecd7e0bb71e4937cc1c5
          linux-amd64: 19a616775a22b672e036e717a0a728eae14bd10af79a619dfdd7510ef2eaccb3
    - locator:
        id: com.palantir.godel-refreshables-plugin:refreshables-plugin:0.110.0
        checksums:
          darwin-amd64: 7254e8e6262b5d81d0e6d17344389fed554452f569f33193a31c58198a5c739e
          linux-amd64: b458b6cd502c8d6631d7626f1d0394baf32e237268006b1724c80f4aef1cfcb3
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
  paths:
    - godel
    - conjure
