plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-conjure-plugin:conjure-plugin:6.46.0
        checksums:
          darwin-amd64: a24564ea190417eb9eaa1b9efd59fbcdb0a74dcc688361d4840aaeeba1e9d472
          linux-amd64: a16ada683207388d1fc2395c68ab610c25f1459990c26baa5816f5a1b19f520a
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.25.0
        checksums:
          darwin-amd64: 660a5b0cf5b155e640d3484bc330d49fc5bfd0ab8c26fd62af1e8d64b093fcee
          linux-amd64: ddd80a26dc1d3cd23f32a2ef57bddc5f5e2f1b17a5c2c3b18a997ac5e59281b9
    - locator:
        id: com.palantir.godel-refreshables-plugin:refreshables-plugin:0.127.0
        checksums:
          darwin-amd64: e1285606f9ff52a92588e3edc027839bf58ab3a3f6e38f87c72307e148acaf2a
          linux-amd64: 589b8898586c3f1d38f3bb03924975a65a2547b528e6fcb436da0d6073134f91
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
  paths:
    - godel
    - conjure
