plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-conjure-plugin:conjure-plugin:6.32.0
        checksums:
          darwin-amd64: 4658f0d95921a32055156b8cb5ab63ffaf32b02c332f34bd9e763b552e521f60
          linux-amd64: be99987048ecc2893ab6dbf0efc1fb7b8c6155aaff9f59b9a5445efd72ddb178
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.14.0
        checksums:
          darwin-amd64: a653ebeaa92a3b4b0efeeddc9b3c8b6c2f40144f80abbebffe6586f567f0dd6f
          linux-amd64: 47c23b17acbc6e3d08428024a0ef617dc2f1d701d72e6c5fe7b711215ec78a00
    - locator:
        id: com.palantir.godel-refreshables-plugin:refreshables-plugin:0.79.0
        checksums:
          darwin-amd64: 9bf754e07a89760862abb24880047ffa4b4928e1d85b15d6eda2b6030a0122d2
          linux-amd64: ef97c4a93486654d95b73b0a38480d0e19e0257dc6c78558e8c2df6482f8b576
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
  paths:
    - godel
    - conjure
