plugins:
  resolvers:
    - https://palantir.bintray.com/releases/{{GroupPath}}/{{Product}}/{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-conjure-plugin:conjure-plugin:6.5.0
        checksums:
          darwin-amd64: 2295c5aa0423cb834e74e95a47a9269940c189b59398144e89574e83097791cf
          linux-amd64: ceab0cb366e2fc6923757044615dbf79eb87141587c0ee10750768f86250a813
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.1.0
        checksums:
          darwin-amd64: e819a8738bbe6356b8d544a8b45a2d1157339f0d9f019323b0b26d4f1176ea4d
          linux-amd64: c820d4fcdcf338641bf8e9b4b72d238395538f7f3d1dd86855cb38cfb93465dc
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
  paths:
    - godel
    - conjure
