plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-conjure-plugin:conjure-plugin:6.31.0
        checksums:
          darwin-amd64: 22ad30a32c15148f3acb7c34d0c6edd2ffb9a9f60d0bb8b0b1f19dba14476ea9
          linux-amd64: b1978f748d1ee679bcb8b1f87f8c770084eff1b4549e6b5e8c56e60d659ffcd7
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.11.0
        checksums:
          darwin-amd64: 5140c4ad8bfcb5cd081669fa951baa9e9c90223e2c4b2eba0cd9e00e778a069c
          linux-amd64: a0277b508c27dd6eefadf0b5a1d261bb21ba8faa4279043cbeecfb0d1cd5c94d
    - locator:
        id: com.palantir.godel-refreshables-plugin:refreshables-plugin:0.69.0
        checksums:
          darwin-amd64: be35a9a4ad10f0a84dfb0af07c85496879d6664ae3d2613bdc5c92092dc7e5c7
          linux-amd64: de579af199faac5586866964a9e2e45e1c35a63dab46d1dcb59b36eb0d2343d3
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
  paths:
    - godel
    - conjure
