plugins:
  resolvers:
    - https://palantir.bintray.com/releases/{{GroupPath}}/{{Product}}/{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-conjure-plugin:conjure-plugin:6.4.0
        checksums:
          darwin-amd64: 36bcf01c59946900e0c765f0a67f0e3270cf1bbad54cc7f4f72f746d20da5575
          linux-amd64: 559c3ac34f9fecae4746b1dc37970848a5995a4d628e5fa9da50062b0e86bc21
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.1.0
        checksums:
          darwin-amd64: e819a8738bbe6356b8d544a8b45a2d1157339f0d9f019323b0b26d4f1176ea4d
          linux-amd64: c820d4fcdcf338641bf8e9b4b72d238395538f7f3d1dd86855cb38cfb93465dc
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
  paths:
    - godel
    - conjure
