plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-conjure-plugin:conjure-plugin:6.67.0
        checksums:
          darwin-amd64: 3549b0b72a2bbdfcc2aba4fc3c1ba98e4067ce30c467ce21a95f3983b9fcd3b2
          linux-amd64: 3deb37e9c932348d49673b907f7265c6e40c44af0c381b974f57beaa20b2e29f
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.43.0
        checksums:
          darwin-amd64: 39765ffae9b437a09b98d6377bdd7af945a69a8dbb028c1f3659924bfade35cd
          linux-amd64: 4d0b71b29e946d37935664a4e53082f6af46a71a17fd35cbf934364f45507e76
    - locator:
        id: com.palantir.godel-refreshables-plugin:refreshables-plugin:0.227.0
        checksums:
          darwin-amd64: 1abd7ec9fa70a458d4ca72e3ef57e1ab94afc56ecc70f00a2b686d68dc1aa9d0
          linux-amd64: 8238bb21c32405907494b9c8e9988c8a5f7d3dea3fe391f518a55d37708fd3fe
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
  paths:
    - godel
    - conjure
