plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-conjure-plugin:conjure-plugin:6.26.0
        checksums:
          darwin-amd64: cdf109974352277b53f70a47852db32a6724ec1de45b877b0a1385fd91859ee4
          linux-amd64: 0d55cdd384b5266c2c36957f9b0ad13fcef5b96b2225b38a194954ad6a867a2a
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.8.0
        checksums:
          darwin-amd64: b139799cdb6bb4d3e440f24631c1bfe7fc362978fb37663dc45f460c1a0af684
          linux-amd64: 29eac0e09eeea516ad7e1595f69ee87bd8f8ecb72f979f4549ef054131fd62ac
    - locator:
        id: com.palantir.godel-refreshables-plugin:refreshables-plugin:0.61.0
        checksums:
          darwin-amd64: 160f7717f91ab1d6474430196bc4edf1e5c2c4e5d1d2c90bddc671c84d666500
          linux-amd64: 6f3a908b11807c6f7cc538de47379cdea1a9220ae218d9cfa6710a062f8d9ffd
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
  paths:
    - godel
    - conjure
