plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-conjure-plugin:conjure-plugin:6.20.0
        checksums:
          darwin-amd64: ceb654bdcf6fc2aaf7be59fa99b2d55badbaff8180a5504be0dadd1ecfb66354
          linux-amd64: 84493d4472a18ea8df275c64195051771cfc533deacb68a58fdfcb063fe7aaf2
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.5.0
        checksums:
          darwin-amd64: 10fd0994599ce564e1d156671417adf2a1d00c158f0777e352bde31c387f5906
          linux-amd64: fe7ba0d2df44cfca066d5b02f3e1c666dcc112ac6fcca33575cc8bf617e0e1b8
    - locator:
        id: com.palantir.godel-refreshables-plugin:refreshables-plugin:0.41.0
        checksums:
          darwin-amd64: 36d9d79ae672f18c2008a00070e3dcd4312e2cc505ae25713a94880f734c509b
          linux-amd64: 6e15ccdaf6b38876f26c3cba6c56131bae3effdca4fe81eb3ecac4915ce67bc5
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
  paths:
    - godel
    - conjure
