plugins:
  resolvers:
    - https://palantir.bintray.com/releases/{{GroupPath}}/{{Product}}/{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-conjure-plugin:conjure-plugin:6.3.0
        checksums:
          darwin-amd64: c666d42a157fc2ee715f290a0c115ab7a92c56368c6437cad5f4bf971c484cd1
          linux-amd64: a88eb4fc59b32e98d21eab37d71f3333049df9f002998915e7429313185b2005
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.1.0
        checksums:
          darwin-amd64: e819a8738bbe6356b8d544a8b45a2d1157339f0d9f019323b0b26d4f1176ea4d
          linux-amd64: c820d4fcdcf338641bf8e9b4b72d238395538f7f3d1dd86855cb38cfb93465dc
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
  paths:
    - godel
    - conjure
