plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-conjure-plugin:conjure-plugin:6.36.0
        checksums:
          darwin-amd64: d41a0a9b2aba65365d4b427ba1c3b4a569f0e5ac9a67490d9b04aa33d2f5eec7
          linux-amd64: 4d1ca066cf16a40da62229a8059c5ba138b6ff9c5e836ec35a7d0dae0f285a02
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.21.0
        checksums:
          darwin-amd64: 03bc85164aa2d966e6d7dd692b38cc9d0c5c3a7f783c909e30378a14e95316d6
          linux-amd64: b27529dde28285884dd0c15586f8b59a25a9212aa475e32417cdf99ae5469281
    - locator:
        id: com.palantir.godel-refreshables-plugin:refreshables-plugin:0.101.0
        checksums:
          darwin-amd64: aa6f1ef4b259aefe0cc1f3593735aa3aa3cdb1457c1f0601666e4e3864dc5d3c
          linux-amd64: 2c81ae66fb348d91fe22f15192e74ce53cb8baef4e31b51ae9a3aacdd4c5f0fa
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
  paths:
    - godel
    - conjure
