plugins:
  resolvers:
    - "https://palantir.bintray.com/releases/{{GroupPath}}/{{Product}}/{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz"
  plugins:
    - locator:
        id: "com.palantir.godel-conjure-plugin:conjure-plugin:4.0.0"
        checksums:
          darwin-amd64: 90869bfd1e886c36fe9796e0964eb5e3adb39b3b5c68ea3a4f171b9423243200
          linux-amd64: b12b4a9659726db42d235a2267518c76e60c3e9496ba86a2ba97af5ebee69a7f
    - locator:
        id: "com.palantir.godel-dep-plugin:dep-plugin:1.1.0"
        checksums:
          darwin-amd64: 946b0def510a7e94b46bb635a67f00c05243505e2a2ef9b0b7dab45b0437be1f
          linux-amd64: cc2729e7f25c0121f841e237238c11514ee4c1376c458a1c4997ee86de17b209
exclude:
  names:
  - \..+
  - vendor
  paths:
  - godel
  - conjure
  - witchcraft/internal/negroni
