plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-conjure-plugin:conjure-plugin:6.22.0
        checksums:
          darwin-amd64: 9f063291176464bb321fb5340c6ec9c5282176c8e07f6d2f3a6952702bad877c
          linux-amd64: 2555fa54c902bbfd25b775321e1a0930c069681d62e84503c8c7adde69e8a4f8
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.8.0
        checksums:
          darwin-amd64: b139799cdb6bb4d3e440f24631c1bfe7fc362978fb37663dc45f460c1a0af684
          linux-amd64: 29eac0e09eeea516ad7e1595f69ee87bd8f8ecb72f979f4549ef054131fd62ac
    - locator:
        id: com.palantir.godel-refreshables-plugin:refreshables-plugin:0.56.0
        checksums:
          darwin-amd64: 175c1e79a86231091882bf22384195a1027c54bf0002396ffb30d6ea74a56be1
          linux-amd64: e3b988b2af2f8ab18ba06b4665c014160b83110b0fe13ac8ba47c82efd0f06be
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
  paths:
    - godel
    - conjure
