plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-conjure-plugin:conjure-plugin:6.61.0
        checksums:
          darwin-amd64: 34281c165006a2fd07723c0dc41498c62bc25e7dcedef3a65256a8e5e62c5669
          linux-amd64: 6994e601829232477a4589ebca17e3080a32c42b0f08d2bbb683cb1f88074fee
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.38.0
        checksums:
          darwin-amd64: a752036a5a9c7e00f40f8cbacc9b7a9539cd5ad4c8bea2a462148890ac1d5407
          linux-amd64: d407ed2eb3d14ceed09f75562e6948e36f55b759529ead5b0dc33169508c1120
    - locator:
        id: com.palantir.godel-refreshables-plugin:refreshables-plugin:0.206.0
        checksums:
          darwin-amd64: f12b48590f84041665ca5da43a3dd42c4782dac072180e1ff5863690abd6b884
          linux-amd64: d7538f21f3a33878d1db771bc363d9d34eeb7127015927178de46fdec3e9e3c3
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
  paths:
    - godel
    - conjure
