plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-conjure-plugin:conjure-plugin:6.71.0
        checksums:
          darwin-amd64: ef2444d51fc20528e10d920447c50bbaba9c364cbcd43390c8942e594d1d159c
          linux-amd64: d70f2e770cfd2b9919a701d1ba6f18e3dc8802059fb074dc3e283cc2e7a01305
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.45.0
        checksums:
          darwin-amd64: 86c00f02a2fa80a2223d492e931c4ec3312b3e0c895822c2f5ed8c0ea7b2e1b9
          linux-amd64: ac50a961c95657a92105c417671b8d18dfe45da0019e72cdac0b9f5938f2ea4c
    - locator:
        id: com.palantir.godel-refreshables-plugin:refreshables-plugin:0.239.0
        checksums:
          darwin-amd64: 6360ae0c6281ab663de080985df0be92b07cb4217919622b0f6b201882ad70e4
          linux-amd64: 79e9bb78c84d2cb19907361c13a4b939271b27a57ab963495850dd738bd4aa3b
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
  paths:
    - godel
    - conjure
