plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-conjure-plugin:conjure-plugin:6.17.0
        checksums:
          darwin-amd64: b7ac5ccf717cf94cf7f5d163f00bf5aadbf7407e61672161190ac67deabfa688
          linux-amd64: e746400a612b765808f4ba7cb0278dc4c6920a8b0d697a6b447d566170ad69cb
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.3.0
        checksums:
          darwin-amd64: 08a65d8db9555c4580dbf6cdfd954ffafc687ecbf5a71a643bc190baa9b774ad
          linux-amd64: dda61df35df69154836b4f6caa14f88d6b1a59acdb99005e5f5de986fa33f37b
    - locator:
        id: com.palantir.godel-refreshables-plugin:refreshables-plugin:0.30.0
        checksums:
          darwin-amd64: f814ece4d787af2c8bab60980250fa67a50493f040ca61e2a2c84178520f5648
          linux-amd64: 22c846686fdeca052f83e5f4e98a21e515615157dc2f4a478932dc82e6af4e89
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
  paths:
    - godel
    - conjure
