plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-conjure-plugin:conjure-plugin:6.52.0
        checksums:
          darwin-amd64: 1c95da54d494a650837776709506dd51734beed04573c78fea1d53815e0fbec4
          linux-amd64: a074787da6aec38ae284197e67d864f6d06b866ed7a2a0f44ec55d3b2b1425d0
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.30.0
        checksums:
          darwin-amd64: c8e00d750c5bf5f9ab375875c6176ee1876bffa19204e106156d91c56d0e8865
          linux-amd64: f8d21b0af44f3dc7d27fd2459c198d55b128a356cb2c3d1b6cb4be2523eb4503
    - locator:
        id: com.palantir.godel-refreshables-plugin:refreshables-plugin:0.155.0
        checksums:
          darwin-amd64: a35127a33af437190b0d2613c83f02c39926179f85d5c6e7253ab62548fe7cba
          linux-amd64: bed1c23f4dc6d308c6252927f4e2f32b6a9da4c69e3230d1570aad52592b0fcc
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
  paths:
    - godel
    - conjure
