plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-conjure-plugin:conjure-plugin:6.57.0
        checksums:
          darwin-amd64: 68f9825a127515908b80c34c52fb67d536cb058710f2225adc4789ec2853dd96
          linux-amd64: f9194ea1e106ea8ee0661f2e02d654e6157b3269c19f2bcff397b574a88ec0b6
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.34.0
        checksums:
          darwin-amd64: 007c0c920eef87c81fc762ef72bb8eba3a6da38d471ce524674f4ee435de7187
          linux-amd64: e85e1df3a13b6b58719b919a92c12cf7f4b5c9d9afab019e656a38cb65b52e12
    - locator:
        id: com.palantir.godel-refreshables-plugin:refreshables-plugin:0.178.0
        checksums:
          darwin-amd64: 90b3cca1b52bc5901e309a1ce91a9c15c866cc757f76a6f8304380d44e9b4d04
          linux-amd64: 45b973e255e077c027d46e4e1954253078991fe97dbf591a311049ba7e036cf1
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
  paths:
    - godel
    - conjure
