plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-conjure-plugin:conjure-plugin:6.20.0
        checksums:
          darwin-amd64: ceb654bdcf6fc2aaf7be59fa99b2d55badbaff8180a5504be0dadd1ecfb66354
          linux-amd64: 84493d4472a18ea8df275c64195051771cfc533deacb68a58fdfcb063fe7aaf2
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.4.0
        checksums:
          darwin-amd64: 394fde518cc913ba808e0e0ecbc00da54ed88f6f71fa57fb1da1836a46b1b74b
          linux-amd64: 110540240a42894f0c76922ee832391938e9f51cac9a0a7c7f24cfcc9f9a34fa
    - locator:
        id: com.palantir.godel-refreshables-plugin:refreshables-plugin:0.37.0
        checksums:
          darwin-amd64: f55caf40cac01e725ff84fd0ddee336b46e096c2f986ac4e7f4a4a3c82386142
          linux-amd64: cfba0290a677ce1a241a446ca9b3fc5e0de0cf550809de7fa03a7698880bf2aa
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
  paths:
    - godel
    - conjure
