plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-conjure-plugin:conjure-plugin:6.54.0
        checksums:
          darwin-amd64: f63eb0f1733df5b3086019d97425171f7e08cc546e9fd69a7384b4245c380cc7
          linux-amd64: ab0d792a5009873846991d3041ef47780f5772362d4d61e21f7b4d8f4ba57334
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.32.0
        checksums:
          darwin-amd64: ed3d1f60b425b7019fe4e1da9b0a2c5ef69f5881416454ae54fa2beb476b2f79
          linux-amd64: c8f5ce8b55fd45e14845201d5003a690caffce8b75d7e8e5354c9fdeea2e32d7
    - locator:
        id: com.palantir.godel-refreshables-plugin:refreshables-plugin:0.163.0
        checksums:
          darwin-amd64: a504764e19e84451257db71ec382c00c2c2a9bc2fd752ebeffd41f898afade88
          linux-amd64: 8d39cf8b2e1e2a69835c2ad5561a9b53b1fc22267bb2771128062d8b1cbb77a1
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
  paths:
    - godel
    - conjure
