plugins:
  resolvers:
    - https://palantir.bintray.com/releases/{{GroupPath}}/{{Product}}/{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-conjure-plugin:conjure-plugin:5.7.0
        checksums:
          darwin-amd64: ce5d84dfeb540f8c6ae1925476fe448b8bf0a0407360bd35b2028c4e2d6df8c1
          linux-amd64: 2436e9731a41ae12744cb8dfee5ac1268135ab4b3f2ac26c58237b9ad67c15c4
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.1.0
        checksums:
          darwin-amd64: e819a8738bbe6356b8d544a8b45a2d1157339f0d9f019323b0b26d4f1176ea4d
          linux-amd64: c820d4fcdcf338641bf8e9b4b72d238395538f7f3d1dd86855cb38cfb93465dc
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
  paths:
    - godel
    - conjure
