plugins:
  resolvers:
    - https://github.com/{{index GroupParts 1}}/{{index GroupParts 2}}/releases/download/v{{Version}}/{{Product}}-{{Version}}-{{OS}}-{{Arch}}.tgz
  plugins:
    - locator:
        id: com.palantir.godel-conjure-plugin:conjure-plugin:6.57.0
        checksums:
          darwin-amd64: 68f9825a127515908b80c34c52fb67d536cb058710f2225adc4789ec2853dd96
          linux-amd64: f9194ea1e106ea8ee0661f2e02d654e6157b3269c19f2bcff397b574a88ec0b6
    - locator:
        id: com.palantir.godel-mod-plugin:mod-plugin:1.34.0
        checksums:
          darwin-amd64: 007c0c920eef87c81fc762ef72bb8eba3a6da38d471ce524674f4ee435de7187
          linux-amd64: e85e1df3a13b6b58719b919a92c12cf7f4b5c9d9afab019e656a38cb65b52e12
    - locator:
        id: com.palantir.godel-refreshables-plugin:refreshables-plugin:0.184.0
        checksums:
          darwin-amd64: a62dac12b5f62dab554b4d3fb733b4ea8275a236f496a69c14bf803d29da8e18
          linux-amd64: 51c8f140a732fad491125b69a8cc69d65815fb318cc28f5d898476580364a14f
environment:
  GO111MODULE: "on"
  GOFLAGS: "-mod=vendor"
exclude:
  names:
    - \..+
    - vendor
  paths:
    - godel
    - conjure
